-- Generated by tools/make_content_sql.py from content/*.json.
-- Paste whole into the Supabase SQL editor and Run once. Idempotent:
-- re-running updates rows in place by stable keys and orphans nothing.
begin;

-- Schema alignment, idempotent: the base schema predates these.
alter table certificate_courses add column if not exists published boolean not null default true;
alter table certificate_courses alter column hours set default 0;
create unique index if not exists course_videos_course_ord_key on course_videos (course_id, ord);
create unique index if not exists quiz_questions_video_ord_key on quiz_questions (video_id, ord);
create unique index if not exists final_qa_questions_course_ord_key on final_qa_questions (course_id, ord);

-- ===== Fathering Fundamentals (fundamentals) =====
do $$
declare cid uuid; vid uuid;
begin
  select id into cid from certificate_courses where slug = 'fundamentals';
  if cid is null then
    insert into certificate_courses (slug, title, hours, published) values ('fundamentals', 'Fathering Fundamentals', 0, false) returning id into cid;
  else
    update certificate_courses set title = 'Fathering Fundamentals' where id = cid;
  end if;

  -- session 1: Why Presence Wins
  select id into vid from course_videos where course_id = cid and ord = 1;
  if vid is null then
    insert into course_videos (course_id, ord, title, video_url, duration_seconds) values (cid, 1, 'Why Presence Wins', 'pending', 0) returning id into vid;
  else
    update course_videos set title = 'Why Presence Wins', video_url = 'pending', duration_seconds = 0 where id = vid;
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 1) then
    update quiz_questions set prompt = 'What does this course treat as the engine that everything else in fathering rides on?', choices = '["Providing financially", "Presence: showing up, attention on", "Having the right answers", "Strict discipline"]'::jsonb, correct_index = 1 where video_id = vid and ord = 1;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 1, 'What does this course treat as the engine that everything else in fathering rides on?', '["Providing financially", "Presence: showing up, attention on", "Having the right answers", "Strict discipline"]'::jsonb, 1);
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 2) then
    update quiz_questions set prompt = 'A father is home every evening but on his phone through dinner. By this session''s standard, what is he giving his children?', choices = '["Presence, because he is in the room", "Proximity without presence", "Quality time"]'::jsonb, correct_index = 1 where video_id = vid and ord = 2;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 2, 'A father is home every evening but on his phone through dinner. By this session''s standard, what is he giving his children?', '["Presence, because he is in the room", "Proximity without presence", "Quality time"]'::jsonb, 1);
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 3) then
    update quiz_questions set prompt = 'What is the practical move this session asks of you first?', choices = '["Plan a big outing to make up for lost time", "Pick one daily window and put your attention fully on your child in it", "Wait until life is less busy"]'::jsonb, correct_index = 1 where video_id = vid and ord = 3;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 3, 'What is the practical move this session asks of you first?', '["Plan a big outing to make up for lost time", "Pick one daily window and put your attention fully on your child in it", "Wait until life is less busy"]'::jsonb, 1);
  end if;

  -- session 2: A Schedule They Can Trust
  select id into vid from course_videos where course_id = cid and ord = 2;
  if vid is null then
    insert into course_videos (course_id, ord, title, video_url, duration_seconds) values (cid, 2, 'A Schedule They Can Trust', 'pending', 0) returning id into vid;
  else
    update course_videos set title = 'A Schedule They Can Trust', video_url = 'pending', duration_seconds = 0 where id = vid;
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 1) then
    update quiz_questions set prompt = 'In this session, what does the calendar function as?', choices = '["A productivity tool", "A promise your children can watch you keep", "A record for your own reference"]'::jsonb, correct_index = 1 where video_id = vid and ord = 1;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 1, 'In this session, what does the calendar function as?', '["A productivity tool", "A promise your children can watch you keep", "A record for your own reference"]'::jsonb, 1);
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 2) then
    update quiz_questions set prompt = 'Which builds a child''s trust fastest, according to the session?', choices = '["Occasional big surprises", "A standing time that happens when you said it would, week after week", "Explaining why you were busy"]'::jsonb, correct_index = 1 where video_id = vid and ord = 2;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 2, 'Which builds a child''s trust fastest, according to the session?', '["Occasional big surprises", "A standing time that happens when you said it would, week after week", "Explaining why you were busy"]'::jsonb, 1);
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 3) then
    update quiz_questions set prompt = 'You have to miss a standing time. What is the move?', choices = '["Skip it quietly; children forget", "Tell them ahead, name the new time, and keep the new time", "Make it up with a gift"]'::jsonb, correct_index = 1 where video_id = vid and ord = 3;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 3, 'You have to miss a standing time. What is the move?', '["Skip it quietly; children forget", "Tell them ahead, name the new time, and keep the new time", "Make it up with a gift"]'::jsonb, 1);
  end if;

  -- session 3: Enter Their World
  select id into vid from course_videos where course_id = cid and ord = 3;
  if vid is null then
    insert into course_videos (course_id, ord, title, video_url, duration_seconds) values (cid, 3, 'Enter Their World', 'pending', 0) returning id into vid;
  else
    update course_videos set title = 'Enter Their World', video_url = 'pending', duration_seconds = 0 where id = vid;
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 1) then
    update quiz_questions set prompt = 'What does awareness look like in practice in this session?', choices = '["Monitoring their grades closely", "Knowing their friends'' names and their inner weather", "Checking their phone"]'::jsonb, correct_index = 1 where video_id = vid and ord = 1;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 1, 'What does awareness look like in practice in this session?', '["Monitoring their grades closely", "Knowing their friends'' names and their inner weather", "Checking their phone"]'::jsonb, 1);
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 2) then
    update quiz_questions set prompt = 'Your child shares a problem. The session''s counsel is to lead with what?', choices = '["A fix, quickly, so they feel helped", "Questions, without fixing", "A story about your own childhood"]'::jsonb, correct_index = 1 where video_id = vid and ord = 2;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 2, 'Your child shares a problem. The session''s counsel is to lead with what?', '["A fix, quickly, so they feel helped", "Questions, without fixing", "A story about your own childhood"]'::jsonb, 1);
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 3) then
    update quiz_questions set prompt = 'Why do questions beat fixes when a child opens up?', choices = '["Questions keep the door open and tell the child their world is worth entering", "Questions save time", "Fixes are usually wrong"]'::jsonb, correct_index = 0 where video_id = vid and ord = 3;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 3, 'Why do questions beat fixes when a child opens up?', '["Questions keep the door open and tell the child their world is worth entering", "Questions save time", "Fixes are usually wrong"]'::jsonb, 0);
  end if;

  -- session 4: Repair Fast, Stand for Something
  select id into vid from course_videos where course_id = cid and ord = 4;
  if vid is null then
    insert into course_videos (course_id, ord, title, video_url, duration_seconds) values (cid, 4, 'Repair Fast, Stand for Something', 'pending', 0) returning id into vid;
  else
    update course_videos set title = 'Repair Fast, Stand for Something', video_url = 'pending', duration_seconds = 0 where id = vid;
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 1) then
    update quiz_questions set prompt = 'What is the repair standard this session sets after a blowup or a broken word?', choices = '["Let time smooth it over", "Own it out loud within twenty-four hours", "Wait for the child to bring it up"]'::jsonb, correct_index = 1 where video_id = vid and ord = 1;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 1, 'What is the repair standard this session sets after a blowup or a broken word?', '["Let time smooth it over", "Own it out loud within twenty-four hours", "Wait for the child to bring it up"]'::jsonb, 1);
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 2) then
    update quiz_questions set prompt = 'What makes discipline build a child instead of frighten one?', choices = '["Making consequences bigger each time", "Values said out loud in calm hours, so correction connects to something known", "Keeping the rules unstated so they stay flexible"]'::jsonb, correct_index = 1 where video_id = vid and ord = 2;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 2, 'What makes discipline build a child instead of frighten one?', '["Making consequences bigger each time", "Values said out loud in calm hours, so correction connects to something known", "Keeping the rules unstated so they stay flexible"]'::jsonb, 1);
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 3) then
    update quiz_questions set prompt = 'A real repair, per this session, sounds most like which of these?', choices = '["I was wrong to yell. That is not how I want to speak to you.", "You know I love you, right?", "Let''s just forget about last night."]'::jsonb, correct_index = 0 where video_id = vid and ord = 3;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 3, 'A real repair, per this session, sounds most like which of these?', '["I was wrong to yell. That is not how I want to speak to you.", "You know I love you, right?", "Let''s just forget about last night."]'::jsonb, 0);
  end if;

  -- session 5: Your Own Father, Your Ninety Days
  select id into vid from course_videos where course_id = cid and ord = 5;
  if vid is null then
    insert into course_videos (course_id, ord, title, video_url, duration_seconds) values (cid, 5, 'Your Own Father, Your Ninety Days', 'pending', 0) returning id into vid;
  else
    update course_videos set title = 'Your Own Father, Your Ninety Days', video_url = 'pending', duration_seconds = 0 where id = vid;
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 1) then
    update quiz_questions set prompt = 'Why does this course end by looking at the fathering you received?', choices = '["To assign blame accurately", "Because every man fathers out of an inheritance, and seeing it clearly is how you choose what continues", "Because history repeats no matter what"]'::jsonb, correct_index = 1 where video_id = vid and ord = 1;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 1, 'Why does this course end by looking at the fathering you received?', '["To assign blame accurately", "Because every man fathers out of an inheritance, and seeing it clearly is how you choose what continues", "Because history repeats no matter what"]'::jsonb, 1);
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 2) then
    update quiz_questions set prompt = 'Why does no man hold a standard alone in this course?', choices = '["Standards spoken to another man hold better under load than private vows", "Accountability is a program requirement", "Other men have better answers"]'::jsonb, correct_index = 0 where video_id = vid and ord = 2;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 2, 'Why does no man hold a standard alone in this course?', '["Standards spoken to another man hold better under load than private vows", "Accountability is a program requirement", "Other men have better answers"]'::jsonb, 0);
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 3) then
    update quiz_questions set prompt = 'What does locking your ninety-day plan mean here?', choices = '["The plan can never change", "You commit to a written plan with one first target and a retake of your baseline at the end", "You memorize the course material"]'::jsonb, correct_index = 1 where video_id = vid and ord = 3;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 3, 'What does locking your ninety-day plan mean here?', '["The plan can never change", "You commit to a written plan with one first target and a retake of your baseline at the end", "You memorize the course material"]'::jsonb, 1);
  end if;
  if exists (select 1 from final_qa_questions where course_id = cid and ord = 1) then
    update final_qa_questions set prompt = 'Name your one daily presence window: when it is, and what you put down to be in it. Then describe one evening this course changed how you showed up in it.' where course_id = cid and ord = 1;
  else
    insert into final_qa_questions (course_id, ord, prompt) values (cid, 1, 'Name your one daily presence window: when it is, and what you put down to be in it. Then describe one evening this course changed how you showed up in it.');
  end if;
  if exists (select 1 from final_qa_questions where course_id = cid and ord = 2) then
    update final_qa_questions set prompt = 'Write the repair you owe or recently made: what happened, what you said or will say out loud, and what you want your child to know about how you handle being wrong.' where course_id = cid and ord = 2;
  else
    insert into final_qa_questions (course_id, ord, prompt) values (cid, 2, 'Write the repair you owe or recently made: what happened, what you said or will say out loud, and what you want your child to know about how you handle being wrong.');
  end if;
  if exists (select 1 from final_qa_questions where course_id = cid and ord = 3) then
    update final_qa_questions set prompt = 'From the fathering you received: name one thing you are keeping on purpose, one thing that stops with you, and the first target of your ninety-day plan.' where course_id = cid and ord = 3;
  else
    insert into final_qa_questions (course_id, ord, prompt) values (cid, 3, 'From the fathering you received: name one thing you are keeping on purpose, one thing that stops with you, and the first target of your ninety-day plan.');
  end if;
end $$;

-- ===== Coming Home Present (reentry) =====
do $$
declare cid uuid; vid uuid;
begin
  select id into cid from certificate_courses where slug = 'reentry';
  if cid is null then
    insert into certificate_courses (slug, title, hours, published) values ('reentry', 'Coming Home Present', 0, false) returning id into cid;
  else
    update certificate_courses set title = 'Coming Home Present' where id = cid;
  end if;

  -- session 1: The Body You Bring Home
  select id into vid from course_videos where course_id = cid and ord = 1;
  if vid is null then
    insert into course_videos (course_id, ord, title, video_url, duration_seconds) values (cid, 1, 'The Body You Bring Home', 'pending', 0) returning id into vid;
  else
    update course_videos set title = 'The Body You Bring Home', video_url = 'pending', duration_seconds = 0 where id = vid;
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 1) then
    update quiz_questions set prompt = 'The session says your body did its job where you were. What is the work now?', choices = '["Forgetting that time completely", "Teaching your body that home is not there", "Staying on guard, since habits keep you safe"]'::jsonb, correct_index = 1 where video_id = vid and ord = 1;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 1, 'The session says your body did its job where you were. What is the work now?', '["Forgetting that time completely", "Teaching your body that home is not there", "Staying on guard, since habits keep you safe"]'::jsonb, 1);
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 2) then
    update quiz_questions set prompt = 'A loud noise at home spikes you to full alert. What does this session call that?', choices = '["A character flaw", "A trained response firing where it is no longer needed", "Proof you are not ready"]'::jsonb, correct_index = 1 where video_id = vid and ord = 2;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 2, 'A loud noise at home spikes you to full alert. What does this session call that?', '["A character flaw", "A trained response firing where it is no longer needed", "Proof you are not ready"]'::jsonb, 1);
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 3) then
    update quiz_questions set prompt = 'What is the daily practice this session gives you?', choices = '["Avoiding stressful rooms", "A slow exhale practice that tells your body the threat level here", "Pushing through and ignoring the surge"]'::jsonb, correct_index = 1 where video_id = vid and ord = 3;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 3, 'What is the daily practice this session gives you?', '["Avoiding stressful rooms", "A slow exhale practice that tells your body the threat level here", "Pushing through and ignoring the surge"]'::jsonb, 1);
  end if;

  -- session 2: The First Weeks
  select id into vid from course_videos where course_id = cid and ord = 2;
  if vid is null then
    insert into course_videos (course_id, ord, title, video_url, duration_seconds) values (cid, 2, 'The First Weeks', 'pending', 0) returning id into vid;
  else
    update course_videos set title = 'The First Weeks', video_url = 'pending', duration_seconds = 0 where id = vid;
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 1) then
    update quiz_questions set prompt = 'How does this session tell you to treat the emotional wave of the first weeks?', choices = '["Plan around it; do not grade yourself by it", "Fight it until it passes", "Take it as the truth about how the return is going"]'::jsonb, correct_index = 0 where video_id = vid and ord = 1;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 1, 'How does this session tell you to treat the emotional wave of the first weeks?', '["Plan around it; do not grade yourself by it", "Fight it until it passes", "Take it as the truth about how the return is going"]'::jsonb, 0);
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 2) then
    update quiz_questions set prompt = 'Which plan fits the first weeks, per this session?', choices = '["Pack the calendar to make up for lost time", "Few commitments, kept without fail", "Wait to commit to anything until you feel settled"]'::jsonb, correct_index = 1 where video_id = vid and ord = 2;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 2, 'Which plan fits the first weeks, per this session?', '["Pack the calendar to make up for lost time", "Few commitments, kept without fail", "Wait to commit to anything until you feel settled"]'::jsonb, 1);
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 3) then
    update quiz_questions set prompt = 'A hard day in week two means what?', choices = '["The return is failing", "You are on the wave the session told you to expect", "You need to try harder tomorrow to prove it"]'::jsonb, correct_index = 1 where video_id = vid and ord = 3;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 3, 'A hard day in week two means what?', '["The return is failing", "You are on the wave the session told you to expect", "You need to try harder tomorrow to prove it"]'::jsonb, 1);
  end if;

  -- session 3: The Child Who Grew
  select id into vid from course_videos where course_id = cid and ord = 3;
  if vid is null then
    insert into course_videos (course_id, ord, title, video_url, duration_seconds) values (cid, 3, 'The Child Who Grew', 'pending', 0) returning id into vid;
  else
    update course_videos set title = 'The Child Who Grew', video_url = 'pending', duration_seconds = 0 where id = vid;
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 1) then
    update quiz_questions set prompt = 'Who does this session tell you to get to know?', choices = '["The child you remember", "The child in front of you now", "The child you hoped they would become"]'::jsonb, correct_index = 1 where video_id = vid and ord = 1;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 1, 'Who does this session tell you to get to know?', '["The child you remember", "The child in front of you now", "The child you hoped they would become"]'::jsonb, 1);
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 2) then
    update quiz_questions set prompt = 'Your child''s interests changed completely while you were away. The session''s move is what?', choices = '["Steer them back to what you shared before", "Learn the new world with questions, from the start", "Give it time and let them come to you"]'::jsonb, correct_index = 1 where video_id = vid and ord = 2;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 2, 'Your child''s interests changed completely while you were away. The session''s move is what?', '["Steer them back to what you shared before", "Learn the new world with questions, from the start", "Give it time and let them come to you"]'::jsonb, 1);
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 3) then
    update quiz_questions set prompt = 'Why do questions matter so much at this stage?', choices = '["They show the child you are studying who they actually are now", "They fill awkward silence", "They test what the child remembers about you"]'::jsonb, correct_index = 0 where video_id = vid and ord = 3;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 3, 'Why do questions matter so much at this stage?', '["They show the child you are studying who they actually are now", "They fill awkward silence", "They test what the child remembers about you"]'::jsonb, 0);
  end if;

  -- session 4: Small Deposits
  select id into vid from course_videos where course_id = cid and ord = 4;
  if vid is null then
    insert into course_videos (course_id, ord, title, video_url, duration_seconds) values (cid, 4, 'Small Deposits', 'pending', 0) returning id into vid;
  else
    update course_videos set title = 'Small Deposits', video_url = 'pending', duration_seconds = 0 where id = vid;
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 1) then
    update quiz_questions set prompt = 'What beats what, in this session''s rule for rebuilding trust?', choices = '["Big and rare beats small and often", "Small and often beats big and rare", "Words beat actions early on"]'::jsonb, correct_index = 1 where video_id = vid and ord = 1;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 1, 'What beats what, in this session''s rule for rebuilding trust?', '["Big and rare beats small and often", "Small and often beats big and rare", "Words beat actions early on"]'::jsonb, 1);
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 2) then
    update quiz_questions set prompt = 'Which is a deposit, as this session means it?', choices = '["A ten-minute call that happens exactly when you said", "A large gift on a birthday", "A promise about next year"]'::jsonb, correct_index = 0 where video_id = vid and ord = 2;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 2, 'Which is a deposit, as this session means it?', '["A ten-minute call that happens exactly when you said", "A large gift on a birthday", "A promise about next year"]'::jsonb, 0);
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 3) then
    update quiz_questions set prompt = 'Why do small deposits work on a child''s trust?', choices = '["Children prefer small things", "Each kept promise is evidence, and evidence stacks", "They cost less"]'::jsonb, correct_index = 1 where video_id = vid and ord = 3;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 3, 'Why do small deposits work on a child''s trust?', '["Children prefer small things", "Each kept promise is evidence, and evidence stacks", "They cost less"]'::jsonb, 1);
  end if;

  -- session 5: When It Breaks
  select id into vid from course_videos where course_id = cid and ord = 5;
  if vid is null then
    insert into course_videos (course_id, ord, title, video_url, duration_seconds) values (cid, 5, 'When It Breaks', 'pending', 0) returning id into vid;
  else
    update course_videos set title = 'When It Breaks', video_url = 'pending', duration_seconds = 0 where id = vid;
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 1) then
    update quiz_questions set prompt = 'How does this session treat rupture between you and your child?', choices = '["As normal, with repair as the skill", "As rare if you are careful", "As proof the return came too soon"]'::jsonb, correct_index = 0 where video_id = vid and ord = 1;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 1, 'How does this session treat rupture between you and your child?', '["As normal, with repair as the skill", "As rare if you are careful", "As proof the return came too soon"]'::jsonb, 0);
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 2) then
    update quiz_questions set prompt = 'You snapped at your child last night. The session''s next step is what?', choices = '["Give them space for a few days", "Own it out loud, briefly and without excuses, and say what you will do differently", "Do something fun together and move on"]'::jsonb, correct_index = 1 where video_id = vid and ord = 2;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 2, 'You snapped at your child last night. The session''s next step is what?', '["Give them space for a few days", "Own it out loud, briefly and without excuses, and say what you will do differently", "Do something fun together and move on"]'::jsonb, 1);
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 3) then
    update quiz_questions set prompt = 'What does a child learn from watching you repair?', choices = '["That you are unreliable", "That being wrong can be handled honestly, which is itself the teaching", "That they can get away with things too"]'::jsonb, correct_index = 1 where video_id = vid and ord = 3;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 3, 'What does a child learn from watching you repair?', '["That you are unreliable", "That being wrong can be handled honestly, which is itself the teaching", "That they can get away with things too"]'::jsonb, 1);
  end if;

  -- session 6: Keeping Your Word at a Distance
  select id into vid from course_videos where course_id = cid and ord = 6;
  if vid is null then
    insert into course_videos (course_id, ord, title, video_url, duration_seconds) values (cid, 6, 'Keeping Your Word at a Distance', 'pending', 0) returning id into vid;
  else
    update course_videos set title = 'Keeping Your Word at a Distance', video_url = 'pending', duration_seconds = 0 where id = vid;
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 1) then
    update quiz_questions set prompt = 'Why does a kept promise count double from far away, per this session?', choices = '["Distance makes promises harder to check", "Distance strips everything but the promise itself, so keeping it is pure evidence", "Children expect less from far away"]'::jsonb, correct_index = 1 where video_id = vid and ord = 1;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 1, 'Why does a kept promise count double from far away, per this session?', '["Distance makes promises harder to check", "Distance strips everything but the promise itself, so keeping it is pure evidence", "Children expect less from far away"]'::jsonb, 1);
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 2) then
    update quiz_questions set prompt = 'Which promise should you make at a distance?', choices = '["The biggest one you can, to show intent", "Only one you can keep from where you actually are", "None, until you are closer"]'::jsonb, correct_index = 1 where video_id = vid and ord = 2;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 2, 'Which promise should you make at a distance?', '["The biggest one you can, to show intent", "Only one you can keep from where you actually are", "None, until you are closer"]'::jsonb, 1);
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 3) then
    update quiz_questions set prompt = 'You promised a call at seven and something came up at work. What is the move?', choices = '["Call the next day and explain", "Call at seven even for two minutes, or renegotiate before seven, never after", "Text instead"]'::jsonb, correct_index = 1 where video_id = vid and ord = 3;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 3, 'You promised a call at seven and something came up at work. What is the move?', '["Call the next day and explain", "Call at seven even for two minutes, or renegotiate before seven, never after", "Text instead"]'::jsonb, 1);
  end if;

  -- session 7: The Reunion Day
  select id into vid from course_videos where course_id = cid and ord = 7;
  if vid is null then
    insert into course_videos (course_id, ord, title, video_url, duration_seconds) values (cid, 7, 'The Reunion Day', 'pending', 0) returning id into vid;
  else
    update course_videos set title = 'The Reunion Day', video_url = 'pending', duration_seconds = 0 where id = vid;
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 1) then
    update quiz_questions set prompt = 'What does this session have you build before the day comes?', choices = '["A speech about the future", "A first-hour plan, rehearsed", "A list of questions for the child"]'::jsonb, correct_index = 1 where video_id = vid and ord = 1;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 1, 'What does this session have you build before the day comes?', '["A speech about the future", "A first-hour plan, rehearsed", "A list of questions for the child"]'::jsonb, 1);
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 2) then
    update quiz_questions set prompt = 'If the child pulls away on reunion day, the session says that is what?', choices = '["The answer", "The start, not the answer", "A sign to give the plan up"]'::jsonb, correct_index = 1 where video_id = vid and ord = 2;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 2, 'If the child pulls away on reunion day, the session says that is what?', '["The answer", "The start, not the answer", "A sign to give the plan up"]'::jsonb, 1);
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 3) then
    update quiz_questions set prompt = 'Which first hour fits this session''s counsel?', choices = '["Low pressure, an ordinary shared activity, exits allowed", "A big celebration with everyone there", "A serious talk about everything that happened"]'::jsonb, correct_index = 0 where video_id = vid and ord = 3;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 3, 'Which first hour fits this session''s counsel?', '["Low pressure, an ordinary shared activity, exits allowed", "A big celebration with everyone there", "A serious talk about everything that happened"]'::jsonb, 0);
  end if;

  -- session 8: The Long Return
  select id into vid from course_videos where course_id = cid and ord = 8;
  if vid is null then
    insert into course_videos (course_id, ord, title, video_url, duration_seconds) values (cid, 8, 'The Long Return', 'pending', 0) returning id into vid;
  else
    update course_videos set title = 'The Long Return', video_url = 'pending', duration_seconds = 0 where id = vid;
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 1) then
    update quiz_questions set prompt = 'What is the return, in this course''s final frame?', choices = '["A day you get right or wrong", "A season you work, deposit by deposit", "A test the child administers"]'::jsonb, correct_index = 1 where video_id = vid and ord = 1;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 1, 'What is the return, in this course''s final frame?', '["A day you get right or wrong", "A season you work, deposit by deposit", "A test the child administers"]'::jsonb, 1);
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 2) then
    update quiz_questions set prompt = 'What carries the return through month three and beyond?', choices = '["The emotion of the reunion", "The routines: standing times, kept promises, fast repairs", "The child''s forgiveness"]'::jsonb, correct_index = 1 where video_id = vid and ord = 2;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 2, 'What carries the return through month three and beyond?', '["The emotion of the reunion", "The routines: standing times, kept promises, fast repairs", "The child''s forgiveness"]'::jsonb, 1);
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 3) then
    update quiz_questions set prompt = 'When the old pattern gets tested and you hold, what does the session call that?', choices = '["Luck", "The line holding, which is what change looks like from inside", "A sign the work is finished"]'::jsonb, correct_index = 1 where video_id = vid and ord = 3;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 3, 'When the old pattern gets tested and you hold, what does the session call that?', '["Luck", "The line holding, which is what change looks like from inside", "A sign the work is finished"]'::jsonb, 1);
  end if;
  if exists (select 1 from final_qa_questions where course_id = cid and ord = 1) then
    update final_qa_questions set prompt = 'Describe your body''s alarm firing at home since you started this course: the trigger, what the old response would have been, and what you did instead.' where course_id = cid and ord = 1;
  else
    insert into final_qa_questions (course_id, ord, prompt) values (cid, 1, 'Describe your body''s alarm firing at home since you started this course: the trigger, what the old response would have been, and what you did instead.');
  end if;
  if exists (select 1 from final_qa_questions where course_id = cid and ord = 2) then
    update final_qa_questions set prompt = 'List the small deposits you have running right now: what you promised, to which child, and your record of keeping each one. What is the next deposit you will add?' where course_id = cid and ord = 2;
  else
    insert into final_qa_questions (course_id, ord, prompt) values (cid, 2, 'List the small deposits you have running right now: what you promised, to which child, and your record of keeping each one. What is the next deposit you will add?');
  end if;
  if exists (select 1 from final_qa_questions where course_id = cid and ord = 3) then
    update final_qa_questions set prompt = 'Write your first-hour plan for the reunion, or describe how the first hour actually went: the setting, your opening move, and your plan if the child pulls away.' where course_id = cid and ord = 3;
  else
    insert into final_qa_questions (course_id, ord, prompt) values (cid, 3, 'Write your first-hour plan for the reunion, or describe how the first hour actually went: the setting, your opening move, and your plan if the child pulls away.');
  end if;
end $$;

-- ===== Steady Under Pressure (anger) =====
do $$
declare cid uuid; vid uuid;
begin
  select id into cid from certificate_courses where slug = 'anger';
  if cid is null then
    insert into certificate_courses (slug, title, hours, published) values ('anger', 'Steady Under Pressure', 0, false) returning id into cid;
  else
    update certificate_courses set title = 'Steady Under Pressure' where id = cid;
  end if;

  -- session 1: The Alarm System
  select id into vid from course_videos where course_id = cid and ord = 1;
  if vid is null then
    insert into course_videos (course_id, ord, title, video_url, duration_seconds) values (cid, 1, 'The Alarm System', 'pending', 0) returning id into vid;
  else
    update course_videos set title = 'The Alarm System', video_url = 'pending', duration_seconds = 0 where id = vid;
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 1) then
    update quiz_questions set prompt = 'What does this session call the surge you feel when anger hits?', choices = '["A signal, not an order", "A weakness to eliminate", "An order your body must obey"]'::jsonb, correct_index = 0 where video_id = vid and ord = 1;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 1, 'What does this session call the surge you feel when anger hits?', '["A signal, not an order", "A weakness to eliminate", "An order your body must obey"]'::jsonb, 0);
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 2) then
    update quiz_questions set prompt = 'Why does the surge arrive faster than your thinking?', choices = '["Because you have not trained enough yet", "Because the alarm system is built to fire before deliberation; the skill is what happens next", "Because the situation is truly dangerous"]'::jsonb, correct_index = 1 where video_id = vid and ord = 2;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 2, 'Why does the surge arrive faster than your thinking?', '["Because you have not trained enough yet", "Because the alarm system is built to fire before deliberation; the skill is what happens next", "Because the situation is truly dangerous"]'::jsonb, 1);
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 3) then
    update quiz_questions set prompt = 'What is the first skill this course builds on top of the alarm?', choices = '["Avoiding every trigger", "Noticing the surge early enough to choose", "Explaining your anger to others"]'::jsonb, correct_index = 1 where video_id = vid and ord = 3;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 3, 'What is the first skill this course builds on top of the alarm?', '["Avoiding every trigger", "Noticing the surge early enough to choose", "Explaining your anger to others"]'::jsonb, 1);
  end if;

  -- session 2: The Pause and the Exhale
  select id into vid from course_videos where course_id = cid and ord = 2;
  if vid is null then
    insert into course_videos (course_id, ord, title, video_url, duration_seconds) values (cid, 2, 'The Pause and the Exhale', 'pending', 0) returning id into vid;
  else
    update course_videos set title = 'The Pause and the Exhale', video_url = 'pending', duration_seconds = 0 where id = vid;
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 1) then
    update quiz_questions set prompt = 'What do six seconds and a long exhale buy you, per this session?', choices = '["Your judgment back", "The other person''s apology", "The end of the feeling"]'::jsonb, correct_index = 0 where video_id = vid and ord = 1;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 1, 'What do six seconds and a long exhale buy you, per this session?', '["Your judgment back", "The other person''s apology", "The end of the feeling"]'::jsonb, 0);
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 2) then
    update quiz_questions set prompt = 'Why the exhale specifically?', choices = '["It looks calm to others", "A long slow exhale signals the body to stand down faster than willpower does", "It gives you something to count"]'::jsonb, correct_index = 1 where video_id = vid and ord = 2;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 2, 'Why the exhale specifically?', '["It looks calm to others", "A long slow exhale signals the body to stand down faster than willpower does", "It gives you something to count"]'::jsonb, 1);
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 3) then
    update quiz_questions set prompt = 'When is the pause practiced so it works under load?', choices = '["Only in the heat of real conflict", "In the boring hours, daily, so it is there when the surge comes", "Once, at the start of the course"]'::jsonb, correct_index = 1 where video_id = vid and ord = 3;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 3, 'When is the pause practiced so it works under load?', '["Only in the heat of real conflict", "In the boring hours, daily, so it is there when the surge comes", "Once, at the start of the course"]'::jsonb, 1);
  end if;

  -- session 3: The Step Away
  select id into vid from course_videos where course_id = cid and ord = 3;
  if vid is null then
    insert into course_videos (course_id, ord, title, video_url, duration_seconds) values (cid, 3, 'The Step Away', 'pending', 0) returning id into vid;
  else
    update course_videos set title = 'The Step Away', video_url = 'pending', duration_seconds = 0 where id = vid;
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 1) then
    update quiz_questions set prompt = 'What is the purpose of stepping away in this session?', choices = '["To win the argument by leaving", "To come back; the step away serves the return", "To show how upset you are"]'::jsonb, correct_index = 1 where video_id = vid and ord = 1;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 1, 'What is the purpose of stepping away in this session?', '["To win the argument by leaving", "To come back; the step away serves the return", "To show how upset you are"]'::jsonb, 1);
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 2) then
    update quiz_questions set prompt = 'What makes a step away different from storming out?', choices = '["Volume", "Saying where you are going and when you are coming back", "Nothing; they are the same"]'::jsonb, correct_index = 1 where video_id = vid and ord = 2;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 2, 'What makes a step away different from storming out?', '["Volume", "Saying where you are going and when you are coming back", "Nothing; they are the same"]'::jsonb, 1);
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 3) then
    update quiz_questions set prompt = 'You feel yourself flooding mid-conversation with your child. Which is the session''s move?', choices = '["Push through so they know you care", "Name it, step out briefly, return when you said", "End the conversation for the night"]'::jsonb, correct_index = 1 where video_id = vid and ord = 3;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 3, 'You feel yourself flooding mid-conversation with your child. Which is the session''s move?', '["Push through so they know you care", "Name it, step out briefly, return when you said", "End the conversation for the night"]'::jsonb, 1);
  end if;

  -- session 4: Naming It
  select id into vid from course_videos where course_id = cid and ord = 4;
  if vid is null then
    insert into course_videos (course_id, ord, title, video_url, duration_seconds) values (cid, 4, 'Naming It', 'pending', 0) returning id into vid;
  else
    update course_videos set title = 'Naming It', video_url = 'pending', duration_seconds = 0 where id = vid;
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 1) then
    update quiz_questions set prompt = 'Why does saying the feeling out loud matter, per this session?', choices = '["So you do not have to show it instead", "So others feel responsible for it", "It does not; feelings should stay private"]'::jsonb, correct_index = 0 where video_id = vid and ord = 1;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 1, 'Why does saying the feeling out loud matter, per this session?', '["So you do not have to show it instead", "So others feel responsible for it", "It does not; feelings should stay private"]'::jsonb, 0);
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 2) then
    update quiz_questions set prompt = 'Which sentence is naming it, as this session teaches?', choices = '["You are making me angry.", "I am angry right now, and I need a minute before we keep going.", "Everyone needs to calm down."]'::jsonb, correct_index = 1 where video_id = vid and ord = 2;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 2, 'Which sentence is naming it, as this session teaches?', '["You are making me angry.", "I am angry right now, and I need a minute before we keep going.", "Everyone needs to calm down."]'::jsonb, 1);
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 3) then
    update quiz_questions set prompt = 'What does a child learn from a father who names his anger plainly?', choices = '["That anger is shameful", "That big feelings can be handled with words, which becomes their skill too", "That the father is weak"]'::jsonb, correct_index = 1 where video_id = vid and ord = 3;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 3, 'What does a child learn from a father who names his anger plainly?', '["That anger is shameful", "That big feelings can be handled with words, which becomes their skill too", "That the father is weak"]'::jsonb, 1);
  end if;

  -- session 5: The Repair
  select id into vid from course_videos where course_id = cid and ord = 5;
  if vid is null then
    insert into course_videos (course_id, ord, title, video_url, duration_seconds) values (cid, 5, 'The Repair', 'pending', 0) returning id into vid;
  else
    update course_videos set title = 'The Repair', video_url = 'pending', duration_seconds = 0 where id = vid;
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 1) then
    update quiz_questions set prompt = 'What is the standard for owning it, per this session?', choices = '["Out loud, specific, without excuses", "A general apology when things are calm", "Letting actions speak over time"]'::jsonb, correct_index = 0 where video_id = vid and ord = 1;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 1, 'What is the standard for owning it, per this session?', '["Out loud, specific, without excuses", "A general apology when things are calm", "Letting actions speak over time"]'::jsonb, 0);
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 2) then
    update quiz_questions set prompt = 'Which of these is a repair and not an excuse?', choices = '["I was tired; you know how my week was.", "I raised my voice at you. That was wrong, and it is mine to fix.", "I am sorry you got upset."]'::jsonb, correct_index = 1 where video_id = vid and ord = 2;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 2, 'Which of these is a repair and not an excuse?', '["I was tired; you know how my week was.", "I raised my voice at you. That was wrong, and it is mine to fix.", "I am sorry you got upset."]'::jsonb, 1);
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 3) then
    update quiz_questions set prompt = 'Why repair fast instead of letting it fade?', choices = '["Fast repair keeps the rupture from hardening into the relationship''s normal", "Children have short memories", "It gets the discomfort over with"]'::jsonb, correct_index = 0 where video_id = vid and ord = 3;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 3, 'Why repair fast instead of letting it fade?', '["Fast repair keeps the rupture from hardening into the relationship''s normal", "Children have short memories", "It gets the discomfort over with"]'::jsonb, 0);
  end if;

  -- session 6: Steady Habits, Steady Mood
  select id into vid from course_videos where course_id = cid and ord = 6;
  if vid is null then
    insert into course_videos (course_id, ord, title, video_url, duration_seconds) values (cid, 6, 'Steady Habits, Steady Mood', 'pending', 0) returning id into vid;
  else
    update course_videos set title = 'Steady Habits, Steady Mood', video_url = 'pending', duration_seconds = 0 where id = vid;
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 1) then
    update quiz_questions set prompt = 'Where does this session say steadiness is actually built?', choices = '["In dramatic moments of self-control", "In the boring hours: sleep, movement, routine", "In willpower alone"]'::jsonb, correct_index = 1 where video_id = vid and ord = 1;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 1, 'Where does this session say steadiness is actually built?', '["In dramatic moments of self-control", "In the boring hours: sleep, movement, routine", "In willpower alone"]'::jsonb, 1);
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 2) then
    update quiz_questions set prompt = 'Why do sleep and routine belong in an anger course?', choices = '["They are filler", "A depleted body fires the alarm sooner and louder; the habits raise your threshold", "They replace the need for the pause"]'::jsonb, correct_index = 1 where video_id = vid and ord = 2;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 2, 'Why do sleep and routine belong in an anger course?', '["They are filler", "A depleted body fires the alarm sooner and louder; the habits raise your threshold", "They replace the need for the pause"]'::jsonb, 1);
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 3) then
    update quiz_questions set prompt = 'What does this course ask you to leave with?', choices = '["A promise to never feel the surge again", "A trained pause, a named feeling, a fast repair, and daily habits that hold them up", "A list of people who provoke you"]'::jsonb, correct_index = 1 where video_id = vid and ord = 3;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 3, 'What does this course ask you to leave with?', '["A promise to never feel the surge again", "A trained pause, a named feeling, a fast repair, and daily habits that hold them up", "A list of people who provoke you"]'::jsonb, 1);
  end if;
  if exists (select 1 from final_qa_questions where course_id = cid and ord = 1) then
    update final_qa_questions set prompt = 'Describe one real surge since you started this course: the trigger, where you caught it, what the pause and exhale did, and how the moment ended.' where course_id = cid and ord = 1;
  else
    insert into final_qa_questions (course_id, ord, prompt) values (cid, 1, 'Describe one real surge since you started this course: the trigger, where you caught it, what the pause and exhale did, and how the moment ended.');
  end if;
  if exists (select 1 from final_qa_questions where course_id = cid and ord = 2) then
    update final_qa_questions set prompt = 'Write the repair you made or owe from a moment your anger got ahead of you: the exact words, said or planned, without excuses.' where course_id = cid and ord = 2;
  else
    insert into final_qa_questions (course_id, ord, prompt) values (cid, 2, 'Write the repair you made or owe from a moment your anger got ahead of you: the exact words, said or planned, without excuses.');
  end if;
  if exists (select 1 from final_qa_questions where course_id = cid and ord = 3) then
    update final_qa_questions set prompt = 'Name the two daily habits you are running to raise your threshold, and your honest record of them across the last two weeks.' where course_id = cid and ord = 3;
  else
    insert into final_qa_questions (course_id, ord, prompt) values (cid, 3, 'Name the two daily habits you are running to raise your threshold, and your honest record of them across the last two weeks.');
  end if;
end $$;

-- ===== Same Team (coparenting) =====
do $$
declare cid uuid; vid uuid;
begin
  select id into cid from certificate_courses where slug = 'coparenting';
  if cid is null then
    insert into certificate_courses (slug, title, hours, published) values ('coparenting', 'Same Team', 0, false) returning id into cid;
  else
    update certificate_courses set title = 'Same Team' where id = cid;
  end if;

  -- session 1: One Team for the Children
  select id into vid from course_videos where course_id = cid and ord = 1;
  if vid is null then
    insert into course_videos (course_id, ord, title, video_url, duration_seconds) values (cid, 1, 'One Team for the Children', 'pending', 0) returning id into vid;
  else
    update course_videos set title = 'One Team for the Children', video_url = 'pending', duration_seconds = 0 where id = vid;
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 1) then
    update quiz_questions set prompt = 'What is the one-sentence frame this course runs on?', choices = '["Whatever we are to each other, we are one team for the child", "Keep the peace at any cost", "Win the important decisions"]'::jsonb, correct_index = 0 where video_id = vid and ord = 1;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 1, 'What is the one-sentence frame this course runs on?', '["Whatever we are to each other, we are one team for the child", "Keep the peace at any cost", "Win the important decisions"]'::jsonb, 0);
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 2) then
    update quiz_questions set prompt = 'Being one team requires what, per this session?', choices = '["Being friends with the other parent", "Agreeing on everything", "Working the child''s interests together, whatever the history between you"]'::jsonb, correct_index = 2 where video_id = vid and ord = 2;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 2, 'Being one team requires what, per this session?', '["Being friends with the other parent", "Agreeing on everything", "Working the child''s interests together, whatever the history between you"]'::jsonb, 2);
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 3) then
    update quiz_questions set prompt = 'What does the child gain when the team holds?', choices = '["Two households pulling one direction, which lowers the load they carry", "Fewer rules", "A guarantee of no conflict"]'::jsonb, correct_index = 0 where video_id = vid and ord = 3;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 3, 'What does the child gain when the team holds?', '["Two households pulling one direction, which lowers the load they carry", "Fewer rules", "A guarantee of no conflict"]'::jsonb, 0);
  end if;

  -- session 2: The Body in Conflict
  select id into vid from course_videos where course_id = cid and ord = 2;
  if vid is null then
    insert into course_videos (course_id, ord, title, video_url, duration_seconds) values (cid, 2, 'The Body in Conflict', 'pending', 0) returning id into vid;
  else
    update course_videos set title = 'The Body in Conflict', video_url = 'pending', duration_seconds = 0 where id = vid;
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 1) then
    update quiz_questions set prompt = 'What does flooded mean in this session?', choices = '["Being sad", "Your body so activated that judgment is gone; continuing makes it worse", "Disagreeing strongly"]'::jsonb, correct_index = 1 where video_id = vid and ord = 1;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 1, 'What does flooded mean in this session?', '["Being sad", "Your body so activated that judgment is gone; continuing makes it worse", "Disagreeing strongly"]'::jsonb, 1);
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 2) then
    update quiz_questions set prompt = 'What is the rule when you notice you are flooded?', choices = '["Push through to resolution", "Pause, about twenty minutes, then resume", "End all contact for the week"]'::jsonb, correct_index = 1 where video_id = vid and ord = 2;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 2, 'What is the rule when you notice you are flooded?', '["Push through to resolution", "Pause, about twenty minutes, then resume", "End all contact for the week"]'::jsonb, 1);
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 3) then
    update quiz_questions set prompt = 'Why twenty minutes, roughly?', choices = '["It is how long the body needs to actually come down; five minutes of silent rehearsing does not count", "It is a rule of the platform", "It gives you time to build your case"]'::jsonb, correct_index = 0 where video_id = vid and ord = 3;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 3, 'Why twenty minutes, roughly?', '["It is how long the body needs to actually come down; five minutes of silent rehearsing does not count", "It is a rule of the platform", "It gives you time to build your case"]'::jsonb, 0);
  end if;

  -- session 3: Businesslike
  select id into vid from course_videos where course_id = cid and ord = 3;
  if vid is null then
    insert into course_videos (course_id, ord, title, video_url, duration_seconds) values (cid, 3, 'Businesslike', 'pending', 0) returning id into vid;
  else
    update course_videos set title = 'Businesslike', video_url = 'pending', duration_seconds = 0 where id = vid;
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 1) then
    update quiz_questions set prompt = 'What are the three marks of businesslike communication here?', choices = '["Short, factual, about the child", "Polite, warm, frequent", "Written, formal, copied to others"]'::jsonb, correct_index = 0 where video_id = vid and ord = 1;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 1, 'What are the three marks of businesslike communication here?', '["Short, factual, about the child", "Polite, warm, frequent", "Written, formal, copied to others"]'::jsonb, 0);
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 2) then
    update quiz_questions set prompt = 'Which message is businesslike?', choices = '["Pickup Friday is 5:30 at school; she has her science fair board with her.", "We need to talk about your choices lately.", "Fine. Whatever works for you, as usual."]'::jsonb, correct_index = 0 where video_id = vid and ord = 2;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 2, 'Which message is businesslike?', '["Pickup Friday is 5:30 at school; she has her science fair board with her.", "We need to talk about your choices lately.", "Fine. Whatever works for you, as usual."]'::jsonb, 0);
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 3) then
    update quiz_questions set prompt = 'Why keep it to the child?', choices = '["Because the old disputes are settled", "Because every message that stays on the child is one that cannot reopen the marriage", "Because feelings are wrong"]'::jsonb, correct_index = 1 where video_id = vid and ord = 3;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 3, 'Why keep it to the child?', '["Because the old disputes are settled", "Because every message that stays on the child is one that cannot reopen the marriage", "Because feelings are wrong"]'::jsonb, 1);
  end if;

  -- session 4: Earning Back Trust
  select id into vid from course_videos where course_id = cid and ord = 4;
  if vid is null then
    insert into course_videos (course_id, ord, title, video_url, duration_seconds) values (cid, 4, 'Earning Back Trust', 'pending', 0) returning id into vid;
  else
    update course_videos set title = 'Earning Back Trust', video_url = 'pending', duration_seconds = 0 where id = vid;
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 1) then
    update quiz_questions set prompt = 'What buys back a co-parent''s trust, per this session?', choices = '["Reliability, kept small promises, over time", "A sincere conversation about the past", "Generosity with money"]'::jsonb, correct_index = 0 where video_id = vid and ord = 1;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 1, 'What buys back a co-parent''s trust, per this session?', '["Reliability, kept small promises, over time", "A sincere conversation about the past", "Generosity with money"]'::jsonb, 0);
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 2) then
    update quiz_questions set prompt = 'How does this session treat court orders and agreements?', choices = '["As obstacles to work around when unfair", "As the floor you never build against; trust is earned inside them, never against them", "As relevant only to lawyers"]'::jsonb, correct_index = 1 where video_id = vid and ord = 2;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 2, 'How does this session treat court orders and agreements?', '["As obstacles to work around when unfair", "As the floor you never build against; trust is earned inside them, never against them", "As relevant only to lawyers"]'::jsonb, 1);
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 3) then
    update quiz_questions set prompt = 'Which is the right first promise to rebuild with?', choices = '["A large one, to prove commitment", "A small one you are certain to keep, then another", "None; let time do it"]'::jsonb, correct_index = 1 where video_id = vid and ord = 3;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 3, 'Which is the right first promise to rebuild with?', '["A large one, to prove commitment", "A small one you are certain to keep, then another", "None; let time do it"]'::jsonb, 1);
  end if;

  -- session 5: One Child, Two Homes
  select id into vid from course_videos where course_id = cid and ord = 5;
  if vid is null then
    insert into course_videos (course_id, ord, title, video_url, duration_seconds) values (cid, 5, 'One Child, Two Homes', 'pending', 0) returning id into vid;
  else
    update course_videos set title = 'One Child, Two Homes', video_url = 'pending', duration_seconds = 0 where id = vid;
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 1) then
    update quiz_questions set prompt = 'Who carries the distance between two homes, per this session?', choices = '["The parents equally", "The child; your job is to lighten the load", "Nobody, if the schedule is fair"]'::jsonb, correct_index = 1 where video_id = vid and ord = 1;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 1, 'Who carries the distance between two homes, per this session?', '["The parents equally", "The child; your job is to lighten the load", "Nobody, if the schedule is fair"]'::jsonb, 1);
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 2) then
    update quiz_questions set prompt = 'Which lightens the child''s load?', choices = '["Asking what happens at the other house", "Letting the child feel free to love both homes out loud", "Keeping the households completely identical"]'::jsonb, correct_index = 1 where video_id = vid and ord = 2;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 2, 'Which lightens the child''s load?', '["Asking what happens at the other house", "Letting the child feel free to love both homes out loud", "Keeping the households completely identical"]'::jsonb, 1);
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 3) then
    update quiz_questions set prompt = 'Your child praises something at the other home. The session''s move is what?', choices = '["Receive it warmly; their ease is the win", "Match it with something better at yours", "Change the subject"]'::jsonb, correct_index = 0 where video_id = vid and ord = 3;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 3, 'Your child praises something at the other home. The session''s move is what?', '["Receive it warmly; their ease is the win", "Match it with something better at yours", "Change the subject"]'::jsonb, 0);
  end if;

  -- session 6: The Handoff
  select id into vid from course_videos where course_id = cid and ord = 6;
  if vid is null then
    insert into course_videos (course_id, ord, title, video_url, duration_seconds) values (cid, 6, 'The Handoff', 'pending', 0) returning id into vid;
  else
    update course_videos set title = 'The Handoff', video_url = 'pending', duration_seconds = 0 where id = vid;
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 1) then
    update quiz_questions set prompt = 'What is the standard for handoffs in this session?', choices = '["Predictable beats perfect", "Quick beats friendly", "Flexible beats scheduled"]'::jsonb, correct_index = 0 where video_id = vid and ord = 1;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 1, 'What is the standard for handoffs in this session?', '["Predictable beats perfect", "Quick beats friendly", "Flexible beats scheduled"]'::jsonb, 0);
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 2) then
    update quiz_questions set prompt = 'What belongs at a handoff?', choices = '["The unresolved topic from last week", "The child''s things, the practical facts, a calm goodbye", "A private word with the other parent about concerns"]'::jsonb, correct_index = 1 where video_id = vid and ord = 2;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 2, 'What belongs at a handoff?', '["The unresolved topic from last week", "The child''s things, the practical facts, a calm goodbye", "A private word with the other parent about concerns"]'::jsonb, 1);
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 3) then
    update quiz_questions set prompt = 'Why does predictability matter so much at the handoff moment?', choices = '["It saves time", "The handoff is where the child feels the team most directly; calm sameness tells them the ground is solid", "It prevents lateness"]'::jsonb, correct_index = 1 where video_id = vid and ord = 3;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 3, 'Why does predictability matter so much at the handoff moment?', '["It saves time", "The handoff is where the child feels the team most directly; calm sameness tells them the ground is solid", "It prevents lateness"]'::jsonb, 1);
  end if;
  if exists (select 1 from final_qa_questions where course_id = cid and ord = 1) then
    update final_qa_questions set prompt = 'Write the last message you sent the other parent, then rewrite it businesslike: short, factual, about the child. What changed?' where course_id = cid and ord = 1;
  else
    insert into final_qa_questions (course_id, ord, prompt) values (cid, 1, 'Write the last message you sent the other parent, then rewrite it businesslike: short, factual, about the child. What changed?');
  end if;
  if exists (select 1 from final_qa_questions where course_id = cid and ord = 2) then
    update final_qa_questions set prompt = 'Describe one flooded moment this course caught: where you felt it, how you paused, and what resuming later made possible.' where course_id = cid and ord = 2;
  else
    insert into final_qa_questions (course_id, ord, prompt) values (cid, 2, 'Describe one flooded moment this course caught: where you felt it, how you paused, and what resuming later made possible.');
  end if;
  if exists (select 1 from final_qa_questions where course_id = cid and ord = 3) then
    update final_qa_questions set prompt = 'Name the small promise you are using to rebuild trust inside the agreement that governs you, and your record of keeping it so far.' where course_id = cid and ord = 3;
  else
    insert into final_qa_questions (course_id, ord, prompt) values (cid, 3, 'Name the small promise you are using to rebuild trust inside the agreement that governs you, and your record of keeping it so far.');
  end if;
end $$;

-- ===== The Man Before You (manhood) =====
do $$
declare cid uuid; vid uuid;
begin
  select id into cid from certificate_courses where slug = 'manhood';
  if cid is null then
    insert into certificate_courses (slug, title, hours, published) values ('manhood', 'The Man Before You', 0, false) returning id into cid;
  else
    update certificate_courses set title = 'The Man Before You' where id = cid;
  end if;

  -- session 1: The Man Before You
  select id into vid from course_videos where course_id = cid and ord = 1;
  if vid is null then
    insert into course_videos (course_id, ord, title, video_url, duration_seconds) values (cid, 1, 'The Man Before You', 'pending', 0) returning id into vid;
  else
    update course_videos set title = 'The Man Before You', video_url = 'pending', duration_seconds = 0 where id = vid;
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 1) then
    update quiz_questions set prompt = 'What is the first act of choosing, per this session?', choices = '["Deciding what kind of father you will be", "Seeing clearly what you were given: kept, missing, harmful, without a verdict on the man", "Forgiving everything"]'::jsonb, correct_index = 1 where video_id = vid and ord = 1;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 1, 'What is the first act of choosing, per this session?', '["Deciding what kind of father you will be", "Seeing clearly what you were given: kept, missing, harmful, without a verdict on the man", "Forgiving everything"]'::jsonb, 1);
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 2) then
    update quiz_questions set prompt = 'Every man fathers out of what, in this session''s frame?', choices = '["His instincts", "An inheritance, received or resisted", "His circumstances"]'::jsonb, correct_index = 1 where video_id = vid and ord = 2;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 2, 'Every man fathers out of what, in this session''s frame?', '["His instincts", "An inheritance, received or resisted", "His circumstances"]'::jsonb, 1);
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 3) then
    update quiz_questions set prompt = 'Why map the inheritance without a verdict on the man who gave it?', choices = '["Because verdicts keep you arguing with the past instead of choosing your carry", "Because the man was probably right", "Because feelings do not belong in the work"]'::jsonb, correct_index = 0 where video_id = vid and ord = 3;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 3, 'Why map the inheritance without a verdict on the man who gave it?', '["Because verdicts keep you arguing with the past instead of choosing your carry", "Because the man was probably right", "Because feelings do not belong in the work"]'::jsonb, 0);
  end if;

  -- session 2: The Account
  select id into vid from course_videos where course_id = cid and ord = 2;
  if vid is null then
    insert into course_videos (course_id, ord, title, video_url, duration_seconds) values (cid, 2, 'The Account', 'pending', 0) returning id into vid;
  else
    update course_videos set title = 'The Account', video_url = 'pending', duration_seconds = 0 where id = vid;
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 1) then
    update quiz_questions set prompt = 'What is the core distinction this session draws?', choices = '["Forgiving versus forgetting", "Resolving a history versus reopening a relationship; the first never requires the second", "Writing versus speaking"]'::jsonb, correct_index = 1 where video_id = vid and ord = 1;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 1, 'What is the core distinction this session draws?', '["Forgiving versus forgetting", "Resolving a history versus reopening a relationship; the first never requires the second", "Writing versus speaking"]'::jsonb, 1);
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 2) then
    update quiz_questions set prompt = 'Where the father is unsafe, unwilling, or gone, the account is settled how?', choices = '["It cannot be settled", "Entirely on paper", "Through another family member"]'::jsonb, correct_index = 1 where video_id = vid and ord = 2;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 2, 'Where the father is unsafe, unwilling, or gone, the account is settled how?', '["It cannot be settled", "Entirely on paper", "Through another family member"]'::jsonb, 1);
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 3) then
    update quiz_questions set prompt = 'What does the letter accomplish even if never sent?', choices = '["It closes the open loop enough to stop living against it or from inside it", "It creates a record for others", "Nothing, unless he reads it"]'::jsonb, correct_index = 0 where video_id = vid and ord = 3;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 3, 'What does the letter accomplish even if never sent?', '["It closes the open loop enough to stop living against it or from inside it", "It creates a record for others", "Nothing, unless he reads it"]'::jsonb, 0);
  end if;

  -- session 3: What Stops With Me
  select id into vid from course_videos where course_id = cid and ord = 3;
  if vid is null then
    insert into course_videos (course_id, ord, title, video_url, duration_seconds) values (cid, 3, 'What Stops With Me', 'pending', 0) returning id into vid;
  else
    update course_videos set title = 'What Stops With Me', video_url = 'pending', duration_seconds = 0 where id = vid;
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 1) then
    update quiz_questions set prompt = 'How does the line break, per this session?', choices = '["By accident, under pressure", "On purpose, out loud", "Slowly, without anyone deciding"]'::jsonb, correct_index = 1 where video_id = vid and ord = 1;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 1, 'How does the line break, per this session?', '["By accident, under pressure", "On purpose, out loud", "Slowly, without anyone deciding"]'::jsonb, 1);
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 2) then
    update quiz_questions set prompt = 'Why speak the line to another man instead of keeping a private vow?', choices = '["A stated line, witnessed, holds better under load than a private vow", "So he can enforce it", "Tradition"]'::jsonb, correct_index = 0 where video_id = vid and ord = 2;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 2, 'Why speak the line to another man instead of keeping a private vow?', '["A stated line, witnessed, holds better under load than a private vow", "So he can enforce it", "Tradition"]'::jsonb, 0);
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 3) then
    update quiz_questions set prompt = 'The line has two columns. What are they?', choices = '["Right and wrong", "Stops with me, and continues through me", "His fault and mine"]'::jsonb, correct_index = 1 where video_id = vid and ord = 3;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 3, 'The line has two columns. What are they?', '["Right and wrong", "Stops with me, and continues through me", "His fault and mine"]'::jsonb, 1);
  end if;

  -- session 4: The Younger Man
  select id into vid from course_videos where course_id = cid and ord = 4;
  if vid is null then
    insert into course_videos (course_id, ord, title, video_url, duration_seconds) values (cid, 4, 'The Younger Man', 'pending', 0) returning id into vid;
  else
    update course_videos set title = 'The Younger Man', video_url = 'pending', duration_seconds = 0 where id = vid;
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 1) then
    update quiz_questions set prompt = 'What is the fastest way to train fathering before fatherhood, per this session?', choices = '["Reading about child development", "Practicing on the younger man already in your life", "Waiting until children come"]'::jsonb, correct_index = 1 where video_id = vid and ord = 1;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 1, 'What is the fastest way to train fathering before fatherhood, per this session?', '["Reading about child development", "Practicing on the younger man already in your life", "Waiting until children come"]'::jsonb, 1);
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 2) then
    update quiz_questions set prompt = 'What is catch-and-return, as trained here?', choices = '["A sport drill", "Meeting a younger man''s bid for attention and returning it with interest, a question for his answer", "Correcting his mistakes quickly"]'::jsonb, correct_index = 1 where video_id = vid and ord = 2;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 2, 'What is catch-and-return, as trained here?', '["A sport drill", "Meeting a younger man''s bid for attention and returning it with interest, a question for his answer", "Correcting his mistakes quickly"]'::jsonb, 1);
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 3) then
    update quiz_questions set prompt = 'What does this session ask you to leave with?', choices = '["A general intention to mentor someday", "One named man you are deliberately investing in", "A schedule of lessons to teach him"]'::jsonb, correct_index = 1 where video_id = vid and ord = 3;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 3, 'What does this session ask you to leave with?', '["A general intention to mentor someday", "One named man you are deliberately investing in", "A schedule of lessons to teach him"]'::jsonb, 1);
  end if;

  -- session 5: The Household You Are Building
  select id into vid from course_videos where course_id = cid and ord = 5;
  if vid is null then
    insert into course_videos (course_id, ord, title, video_url, duration_seconds) values (cid, 5, 'The Household You Are Building', 'pending', 0) returning id into vid;
  else
    update course_videos set title = 'The Household You Are Building', video_url = 'pending', duration_seconds = 0 where id = vid;
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 1) then
    update quiz_questions set prompt = 'When does the household begin, per this session?', choices = '["When someone moves in", "Before anyone moves in; it begins with your word holding", "When children come"]'::jsonb, correct_index = 1 where video_id = vid and ord = 1;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 1, 'When does the household begin, per this session?', '["When someone moves in", "Before anyone moves in; it begins with your word holding", "When children come"]'::jsonb, 1);
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 2) then
    update quiz_questions set prompt = 'What beats a declaration, in this session''s economy of trust?', choices = '["A track record", "A bigger declaration", "An explanation of intent"]'::jsonb, correct_index = 0 where video_id = vid and ord = 2;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 2, 'What beats a declaration, in this session''s economy of trust?', '["A track record", "A bigger declaration", "An explanation of intent"]'::jsonb, 0);
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 3) then
    update quiz_questions set prompt = 'Which is this session''s kind of promise?', choices = '["A vow about the next decade", "A call at the promised time, kept, week after week", "A promise made privately to yourself"]'::jsonb, correct_index = 1 where video_id = vid and ord = 3;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 3, 'Which is this session''s kind of promise?', '["A vow about the next decade", "A call at the promised time, kept, week after week", "A promise made privately to yourself"]'::jsonb, 1);
  end if;

  -- session 6: The Long Line
  select id into vid from course_videos where course_id = cid and ord = 6;
  if vid is null then
    insert into course_videos (course_id, ord, title, video_url, duration_seconds) values (cid, 6, 'The Long Line', 'pending', 0) returning id into vid;
  else
    update course_videos set title = 'The Long Line', video_url = 'pending', duration_seconds = 0 where id = vid;
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 1) then
    update quiz_questions set prompt = 'What does the line holding actually look like, per this session''s closing scene?', choices = '["A dramatic turning point", "An ordinary Tuesday where the calls happen, the question gets asked, and the tested pattern does not repeat", "Public recognition"]'::jsonb, correct_index = 1 where video_id = vid and ord = 1;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 1, 'What does the line holding actually look like, per this session''s closing scene?', '["A dramatic turning point", "An ordinary Tuesday where the calls happen, the question gets asked, and the tested pattern does not repeat", "Public recognition"]'::jsonb, 1);
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 2) then
    update quiz_questions set prompt = 'What does the line plan contain?', choices = '["The account settled, the line stated, the younger man named, the promises running, and an accountability partner", "A list of goals for the year", "The course notes, summarized"]'::jsonb, correct_index = 0 where video_id = vid and ord = 2;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 2, 'What does the line plan contain?', '["The account settled, the line stated, the younger man named, the promises running, and an accountability partner", "A list of goals for the year", "The course notes, summarized"]'::jsonb, 0);
  end if;
  if exists (select 1 from quiz_questions where video_id = vid and ord = 3) then
    update quiz_questions set prompt = 'Who is in the line, per this course''s final frame?', choices = '["Fathers only", "You, already, whether or not children ever come", "Men who finish the course"]'::jsonb, correct_index = 1 where video_id = vid and ord = 3;
  else
    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, 3, 'Who is in the line, per this course''s final frame?', '["Fathers only", "You, already, whether or not children ever come", "Men who finish the course"]'::jsonb, 1);
  end if;
  if exists (select 1 from final_qa_questions where course_id = cid and ord = 1) then
    update final_qa_questions set prompt = 'From your inheritance map: name one thing you received that you are keeping on purpose, one that stops with you, and where each showed up in your conduct this month.' where course_id = cid and ord = 1;
  else
    insert into final_qa_questions (course_id, ord, prompt) values (cid, 1, 'From your inheritance map: name one thing you received that you are keeping on purpose, one that stops with you, and where each showed up in your conduct this month.');
  end if;
  if exists (select 1 from final_qa_questions where course_id = cid and ord = 2) then
    update final_qa_questions set prompt = 'Describe the state of your account: written or in progress, sent or unsent, and what settling it on paper has changed in how you carry it. Contact decisions are yours alone and belong here only if you chose one.' where course_id = cid and ord = 2;
  else
    insert into final_qa_questions (course_id, ord, prompt) values (cid, 2, 'Describe the state of your account: written or in progress, sent or unsent, and what settling it on paper has changed in how you carry it. Contact decisions are yours alone and belong here only if you chose one.');
  end if;
  if exists (select 1 from final_qa_questions where course_id = cid and ord = 3) then
    update final_qa_questions set prompt = 'Name your younger man and your accountability partner, the promises currently running to each, and your record of keeping them.' where course_id = cid and ord = 3;
  else
    insert into final_qa_questions (course_id, ord, prompt) values (cid, 3, 'Name your younger man and your accountability partner, the promises currently running to each, and your record of keeping them.');
  end if;
end $$;

-- Open the four live courses to participants; manhood stays dark until its flag flips.
update certificate_courses set published = true where slug in ('fundamentals', 'reentry', 'anger', 'coparenting');
update certificate_courses set published = false where slug = 'manhood';
commit;
