#!/usr/bin/env python3
"""Compile content/*.json into one idempotent SQL seed for the dashboard
SQL editor (no Python or service key needed at run time). Stable keys:
courses by slug, videos by (course_id, ord), questions by (video_id, ord),
finals by (course_id, ord). Re-running updates in place and never orphans
progress. Regenerate whenever a content JSON changes:
    python3 tools/make_content_sql.py > content/SEED-CONTENT.sql
"""
import json, glob, sys

def q(s):
    return "'" + str(s).replace("'", "''") + "'"

ORDER = ["fundamentals", "reentry", "anger", "coparenting", "manhood"]
PUBLISH = ["fundamentals", "reentry", "anger", "coparenting"]

def main():
    docs = {}
    for p in sorted(glob.glob("content/*.json")):
        if p.endswith("example.json"):
            continue
        d = json.load(open(p))
        docs[d["slug"]] = d
    out = []
    out.append("-- Generated by tools/make_content_sql.py from content/*.json.")
    out.append("-- Paste whole into the Supabase SQL editor and Run once. Idempotent:")
    out.append("-- re-running updates rows in place by stable keys and orphans nothing.")
    out.append("begin;")
    out.append("")
    out.append("-- Schema alignment, idempotent: the base schema predates these.")
    out.append("alter table certificate_courses add column if not exists published boolean not null default true;")
    out.append("alter table certificate_courses alter column hours set default 0;")
    out.append("create unique index if not exists course_videos_course_ord_key on course_videos (course_id, ord);")
    out.append("create unique index if not exists quiz_questions_video_ord_key on quiz_questions (video_id, ord);")
    out.append("create unique index if not exists final_qa_questions_course_ord_key on final_qa_questions (course_id, ord);")
    for slug in ORDER:
        d = docs.get(slug)
        if not d:
            continue
        out.append(f"\n-- ===== {d['title']} ({slug}) =====")
        out.append("do $$")
        out.append("declare cid uuid; vid uuid;")
        out.append("begin")
        out.append(f"  select id into cid from certificate_courses where slug = {q(slug)};")
        out.append("  if cid is null then")
        out.append(f"    insert into certificate_courses (slug, title, hours, published) values ({q(slug)}, {q(d['title'])}, 0, false) returning id into cid;")
        out.append("  else")
        out.append(f"    update certificate_courses set title = {q(d['title'])} where id = cid;")
        out.append("  end if;")
        for v in d["videos"]:
            dur = int(v.get("duration_seconds") or 0)
            ref = q(str(v.get("vimeo") or "pending"))
            out.append(f"\n  -- session {v['ord']}: {v['title']}")
            out.append(f"  select id into vid from course_videos where course_id = cid and ord = {v['ord']};")
            out.append("  if vid is null then")
            out.append(f"    insert into course_videos (course_id, ord, title, video_url, duration_seconds) values (cid, {v['ord']}, {q(v['title'])}, {ref}, {dur}) returning id into vid;")
            out.append("  else")
            out.append(f"    update course_videos set title = {q(v['title'])}, video_url = {ref}, duration_seconds = {dur} where id = vid;")
            out.append("  end if;")
            for j, cq in enumerate(v.get("checkpoint") or [], 1):
                choices = "'" + json.dumps(cq["choices"]).replace("'", "''") + "'::jsonb"
                out.append(f"  if exists (select 1 from quiz_questions where video_id = vid and ord = {j}) then")
                out.append(f"    update quiz_questions set prompt = {q(cq['prompt'])}, choices = {choices}, correct_index = {cq['correct_index']} where video_id = vid and ord = {j};")
                out.append("  else")
                out.append(f"    insert into quiz_questions (video_id, ord, prompt, choices, correct_index) values (vid, {j}, {q(cq['prompt'])}, {choices}, {cq['correct_index']});")
                out.append("  end if;")
        for j, fq in enumerate(d.get("final_qa") or [], 1):
            out.append(f"  if exists (select 1 from final_qa_questions where course_id = cid and ord = {j}) then")
            out.append(f"    update final_qa_questions set prompt = {q(fq['prompt'])} where course_id = cid and ord = {j};")
            out.append("  else")
            out.append(f"    insert into final_qa_questions (course_id, ord, prompt) values (cid, {j}, {q(fq['prompt'])});")
            out.append("  end if;")
        out.append("end $$;")
    pubs = ", ".join(q(s) for s in PUBLISH)
    out.append("\n-- Open the four live courses to participants; manhood stays dark until its flag flips.")
    out.append(f"update certificate_courses set published = true where slug in ({pubs});")
    out.append(f"update certificate_courses set published = false where slug = {q('manhood')};")
    out.append("commit;")
    print("\n".join(out))

if __name__ == "__main__":
    main()
