-- Update father-facing descriptions for the three return-home trainings.
-- Does not change sessions, titles, published, released_at, or development_status.
-- Idempotent: re-run updates description and leader_summary in place by slug.
-- Leaves publish and release flags alone so an already-released Calm row stays usable.

update public.trainings as trainings
set
  description = catalog.description,
  leader_summary = catalog.leader_summary
from (
  values
  (
    'calm-you-can-lend',
    E'This training is for fathers who cycle back into family life after hard stretches away. You may walk through the door still wired. Your body is still high. The people inside did not live that stretch with you. Children borrow the adult nervous system they meet. Other caregivers may borrow it too when they are there. They are optional, not assumed.\n\nPurpose: notice the surge as a body signal, come down with the same short ritual every return, and lend calm the people inside can use. What changes over twelve weeks is the door itself. You stop dumping leftover load onto the first person you see. You arrive as someone the house can borrow steadiness from.\n\nConcrete objectives: name body tells at the door; keep one short come-down every return; stay present once you are down; lend soft voice and proximity to a child before correction; lend calm to whoever is inside when present; repair same day after a snap; protect boring hours without posting calm as a win.\n\nHow a week works: watch one short teaching film, answer one checkpoint, then live one practice that week. The work stays between you and the house. Tone is ordinary house language and Ken Canfield''s I CAN spine (Involvement, Consistency, Awareness, Nurturance). Education for steadiness at home.',
    E'Father returns from hard stretches still wired. Course owns come-down at the door and lending calm outward. Ken Canfield I CAN: Awareness of the surge, Consistency of a return ritual, Involvement once down, Nurturance in calm others can borrow. Success looks like the same short door ritual, soft presence with child (and with whoever is inside when present), same-day repair after a snap, and no peer scorekeeping. Kill the week if come-down becomes a tip he coaches others with and never uses at his own door, or if body language becomes diagnosis talk. Super-admin draft. Not published. Not released. Sponsorship funds the organization, not a preferred seat.'
  ),
  (
    'the-house-that-kept-going',
    E'This training is for fathers who return to a house that kept running while they were gone. Someone kept the routines: a co-parent, kin, a program, or the child. The wound repeats when you walk in and rewrite the rules as if the house waited for your management.\n\nPurpose: see the load in plain words, thank it without a speech, and join the system that already works instead of building a second cockpit. What changes over twelve weeks is how you reenter. You ask before you change a rule. You take one real load the house names. Trust rebuilds through small kept promises and same-day repair when you snap.\n\nConcrete objectives: inventory what kept going without you; name the carrier without assuming who it was; thank once, quietly; ask before changing a house rule; join one existing rhythm; complete one asked load; refuse a parallel ops plan; repair same day with whoever was there; treat trust as lagging, not a same-night score.\n\nHow a week works: one short film, one checkpoint, one lived practice. The work stays between you and the house. Tone is calm, practical, and spouse-safe: no default to a mother or partner. Ken Canfield''s I CAN spine holds the arc. Education for joining a running house.',
    E'Father rejoins a house that ran without him. Carrier may be co-parent, kin, program, or child. Ken Canfield I CAN: Awareness of the load, Involvement in one named load done fully, Consistency of small promises, Nurturance in tone and same-day repair. Success looks like ask-before-rule-change, one joined rhythm, no parallel cockpit, and trust treated as lagging. Kill the week if the carrier becomes a COO or if gratitude covers taking the wheel again. Super-admin draft. Not published. Not released. Sponsorship funds the organization, not a preferred seat.'
  ),
  (
    'knowing-again',
    E'This training is for fathers whose children changed across stretches away. Interests, fears, friends, and how they want you all move. Coming home with yesterday''s picture creates miss after miss. Knowing is never finished when absence cycles.\n\nPurpose: update the picture after every return, ask before you assume, and offer countable presence that fits the child in front of you. What changes over twelve weeks is how you meet them. You stop forcing a reunion script. You make small deposits that match who they are now. Frequency after each stretch beats one big make-up weekend.\n\nConcrete objectives: notice what grew while you were gone; rewrite a private child-now note; ask once and listen longer; treat hesitation as information; make one matching deposit; show up again after the next stretch; put presence before providing; soft-repair a miss with the child same day; optionally use another caregiver as an ally, never as a required messenger; destroy the list at week''s end.\n\nHow a week works: one short film, one checkpoint, one lived practice. If child contact is unavailable, update the private note or rehearse the ask. The work stays between you and the house. Tone is warm, unhurried, and spouse-safe. Ken Canfield''s I CAN spine (Involvement, Consistency, Awareness, Nurturance) holds the work. Education for knowing your child again.',
    E'Father re-knows a child who grew across cyclic absence. Ken Canfield I CAN: Awareness of who they are now, Involvement in matching deposits, Consistency of frequency over make-up weekends, Nurturance with hesitation. Success looks like an updated picture, ask-before-assume, soft presence, and no résumé extraction from the child. Kill the week if knowing becomes a talent review, growth dashboard, or forced reunion. Super-admin draft. Not published. Not released. Sponsorship funds the organization, not a preferred seat.'
  )
) as catalog(slug, description, leader_summary)
where trainings.slug = catalog.slug;
