-- Update stored overview paragraphs for ten trainings by slug.
-- Does not change titles, published, released_at, sessions, videos, or development_status.
-- Idempotent: re-run updates description and leader_summary in place by slug.
-- Does not touch test or flourishingfaith.
-- Return-home three (calm-you-can-lend, the-house-that-kept-going, knowing-again)
-- have no TypeScript seed. This UPDATE is the repo source for those paragraphs.

update public.trainings as trainings
set
  description = catalog.description,
  leader_summary = catalog.leader_summary
from (
  values
  (
    'fundamentals',
    E'A child does not need a speech about the father you meant to be. They need a man they can count on in ordinary hours. You may already be home every night. You may be catching up after time away. Either way, this course is a map you can use the same night you hear it, not a theory class.\n\nKen Canfield spent years sitting with fathers and watching what distinguished the men children could trust. Out of that work came the Seven Secrets: commitment, knowing this child, showing up the same way, protecting and providing, affirming, disciplining with love, and modeling integrity and faith. You begin with the overview and an honest baseline. Then you take the secrets one at a time. Involvement looks like a promise you actually keep. Awareness looks like learning this child''s world instead of the one you remember. Consistency is a rhythm the house can trust. Nurturance is the encouragement and the correction that leave the relationship intact.\n\nEach session is a short teaching film, a checkpoint to make sure the idea landed, and one practice you can try that night. There is no scoreboard, and no room where fathers compare children.',
    E'Ken''s Seven Secrets are the map, used at home the same night. Involvement is a kept promise. Awareness is this child as they are now. Consistency is showing up the same way. Nurturance is affirmation and loving correction. A good week is one practiced move after the film and a child who can count on the same man. If the secrets turn into a lecture, a comparison between children, or a scorecard, bring him back to one secret and one move.'
  ),
  (
    'anger',
    E'Anger is not the enemy. The untrained surge is. Your body fires before your thinking, at home, at work, or in a program, and the people closest to you pay for it if you never learn the gap. Children borrow the nervous system they meet. Anyone else in the house may feel that heat too, when they are there.\n\nThis course teaches you to notice the surge as a signal, not an order. You catch it in the jaw rather than the shout. You take a few silent seconds, stand the body down with a long exhale, and come back as someone the house can stay near. When you snap, you own it the same day in a short, specific apology. Sleep, food, and movement stay in the picture because they hold you. Involvement is coming back into the room on time. Awareness is naming the earliest body cue. Consistency is the pause and the exhale you keep using. Nurturance is the repair that does not reload the fight.\n\nEach week you watch a short film, answer one checkpoint, and live one practice. You can finish the paper even when you cannot sit with your child that week.',
    E'The work is noticing the surge, buying seconds, and repairing the same day. Awareness of body cues, consistency of the pause, involvement once he comes back, nurturance in a short owned apology. A good week looks like catching the jaw, stepping away and returning on time, and closing a snap before sleep. Completion never requires child contact. If he coaches the pause and never uses it, or turns the surge into diagnosis talk, bring him back to his own body and one return.'
  ),
  (
    'reentry',
    E'You walk back into a house that kept going without you. Your body is still carrying the stretch. The people inside did not live it with you. Children borrow the nervous system they meet. Anyone else at home may feel that heat too, when they are there.\n\nComing home present is a season, not a night. This course helps you teach the body that home has a different meaning, meet the child who grew while you were gone, and keep a few promises the house can trust. You plan around the low-energy wave instead of grading the first night. You make small deposits. You repair without pride. Frequency beats a make-up weekend. A pull-away is a start, not a verdict. Involvement is the small deposit. Awareness is the body you bring home and the child in front of you. Consistency is a few kept promises. Nurturance is going first and keeping the repair short.\n\nEach week is a short film, a checkpoint, and one lived practice. Contact helps when it is recent, frequent, and good. When visits are not allowed, the paper still completes.',
    E'The return is a season. The course owns the body at the door, the child who grew, and a few kept promises. Awareness of the body and the present child, consistency of those promises, involvement in small deposits, nurturance in same-day repair. A good week looks like home meaning for old alarms, frequency over intensity, and a pull-away treated as a start. Paper completes when contact is not allowed. If the week becomes a reunion script, a first-night score, or a story about where he was, bring him back to one promise and the child in front of him.'
  ),
  (
    'calm-you-can-lend',
    E'The stretch is over and your body has not heard the news. You walk through the door still high. The people inside did not live what you just carried. A child will borrow whatever you bring. Anyone else in the house may borrow it too, when they are there.\n\nCalm You Can Lend is twelve weeks of coming down at the door before you speak. You learn your own body tells, keep the same short ritual every return, and stay present once you are down. Soft voice and proximity go first. Correction waits. When you snap, you close it the same day. The ordinary hours that hold you are part of the work. None of this is a post or a streak. Involvement is staying in the room after you come down. Awareness is the surge named as a body signal. Consistency is the ritual you do not skip. Nurturance is the calm another person can actually use.\n\nEach week you watch a short film, answer one question, and try one practice.',
    E'Super-admin draft. Not published. Not released. The course owns the door and the calm he lends outward. Awareness of the surge, consistency of the return ritual, involvement once he is down, nurturance in calm others can borrow. A good week is the same short ritual, soft presence with the child and with whoever is inside when they are present, and same-day repair. If he teaches the come-down and never uses it at his own door, or turns body language into diagnosis talk, bring him back to one return. Sponsorship funds the organization, not a preferred seat.'
  ),
  (
    'the-house-that-kept-going',
    E'While you were gone, the house kept going. Someone kept the meals, the bedtime, the school bag. It may have been a co-parent, kin, a program, or the child. The wound opens when you walk in and rewrite the rules as if nothing happened without you.\n\nThis course asks you to see that load in plain words and join what already works. You thank once, quietly. You ask before you change a rule. You take one real load the house names and finish it. Trust comes later than you want. When you snap at the system, you repair the same day with whoever was there. You do not install a second plan beside the one that kept the child. Involvement is the load you actually complete. Awareness is noticing who carried what. Consistency is the small promise kept. Nurturance is the tone when you reenter. No one in this house is assumed to be a mother or a partner.\n\nTwelve weeks of one film, one checkpoint, and one practice.',
    E'Super-admin draft. Not published. Not released. The carrier may be a co-parent, kin, a program, or the child. Awareness of the load, involvement in one named load finished, consistency of small promises, nurturance in tone and same-day repair. A good week is one asked load done, no parallel plan, and trust treated as something that lags. If gratitude becomes cover for taking the wheel, or the keeper of the house is treated like household management, bring him back to one asked load. Sponsorship funds the organization, not a preferred seat.'
  ),
  (
    'knowing-again',
    E'Children change while you are away. Interests, fears, friends, and how they want you all move. Yesterday''s picture of them will miss them, over and over. Knowing your child is never finished when the weeks keep sending you out and bringing you back.\n\nThis course is twelve weeks of meeting the child in front of you. You update a private note about who they are now. You ask once and listen longer. Hesitation is information, not a verdict on your worth. Small deposits that fit them beat a big make-up weekend. Presence comes before providing. If you miss, you repair softly the same day. Another caregiver may help you see what changed. They are an ally when they are part of the week, never a required messenger. Involvement is the matching deposit. Awareness is the updated picture. Consistency is showing up after the next stretch. Nurturance is meeting coolness without forcing a reunion.\n\nWhen you cannot sit with your child, you still complete the week on paper.',
    E'Super-admin draft. Not published. Not released. Awareness of who this child is now, involvement in matching deposits, consistency of frequency over a make-up weekend, nurturance with hesitation. A good week is an honest child-now picture, an ask before an assumption, and presence that extracts nothing for a resume. If knowing becomes a talent review, a growth dashboard, or a forced reunion, bring him back to one question and a closed mouth. Sponsorship funds the organization, not a preferred seat.'
  ),
  (
    'after-action-at-the-door',
    E'The miss already happened. What matters now is the next honest hour. You name it in plain words, own the part that is yours with no defense, and close it the same day with the person who was there. Then you put the clipboard down.\n\nThis course trains a short after-action at home that does not turn the household into a review board. Involvement is walking across the room. Awareness is seeing the miss without spin. Consistency is closing it before you sleep. Nurturance is how the repair lands, and how you stop scoring yourself afterward. Ten minutes is enough. The child who overheard it needs a short, age-fit close. So does the other adult, when they were hit too.\n\nEach week is a short film, a checkpoint, and one lived close. If the repair can be told as a leadership story, it failed the people at your table.',
    E'Super-admin draft. Not published. Not released. Named, owned, closed, same day, then forgotten as a brand. Awareness of the miss, involvement in the close, consistency of same-day timing, nurturance in how it lands. Watch for forum anecdotes, long speeches, and pride dressed as patience. Sponsorship funds the organization, not a preferred seat.'
  ),
  (
    'direct-hours',
    E'Your child does not need another dashboard. They need hours of care the firm cannot have. Direct Hours is a constraint, not a target: one device-down block each weekday you are in town, and one longer block on the weekend.\n\nThe phone leaves the room. Errands with a screen nearby do not count. Travel weeks do not get a pretend win. You restore the first block the day you get back. Involvement is showing up in the window you named. Awareness is knowing what is actually care. Consistency is the weekday and the weekend kept. Nurturance is attention the child can feel, without you scanning their face for payoff.\n\nTwelve weeks of one film, one checkpoint, and one practice. If you are winning Direct Hours in a chat, stop.',
    E'Super-admin draft. Not published. Not released. Hours of care, not a target. Involvement in the named window, awareness of what counts as care, consistency of weekday and weekend, nurturance as attention given rather than reaction harvested. Watch for streaks, hour goals, and virtue speeches about boundaries. A good week is quiet windows the child can count on. Sponsorship funds the organization, not a preferred seat.'
  ),
  (
    'unscored-child',
    E'Almost every hour in a child''s week already has a score. This course protects one hour that does not: no lesson, no sport framed as development, no college signal. You sit with this child and produce nothing you can report.\n\nKen''s work on knowing your child lives here as a weekly hour. You keep a private picture of who they are now, what they are into, what frightens them, and what is coming. You ask questions that are not advice in disguise. You listen longer than you talk. Moods are something you sit with, not something you fix. Involvement is being there. Awareness is the child in the present tense. Consistency is the hour that keeps returning. Nurturance is presence that extracts no return.\n\nIf the hour yields insight you could pitch on Monday, it failed.',
    E'Super-admin draft. Not published. Not released. One unscored hour a week. Awareness of who this child is now, involvement without a resume outcome, consistency of the hour, nurturance as presence with nothing to show. Watch for extraction and insight he wants to report. A good week is the hour kept and the emptiness protected. Sponsorship funds the organization, not a preferred seat.'
  ),
  (
    'midcourse-correction',
    E'You do not stop the ship to become a better father. You make a small turn while it is still moving. Midcourse correction is one countable act a week that means nothing to the firm and cannot be reported as leadership development.\n\nBefore Sunday ends you pick the act. You do it once, plainly, and you do not announce it. Hot weeks move the act earlier, not later. Involvement is the act done. Awareness is knowing what to turn toward. Consistency is twelve quiet weeks. Nurturance is the part you will not put on a slide.\n\nIf it could go in a forum update, pick a different act.',
    E'Super-admin draft. Not published. Not released. One unreportable act a week, done once, not announced. Awareness of what to turn toward, involvement in the act, consistency across quiet weeks, nurturance toward home rather than the firm. Watch for reinvention speeches and fathering told as leadership. Sponsorship funds the organization, not a preferred seat.'
  )
) as catalog(slug, description, leader_summary)
where trainings.slug = catalog.slug
  and trainings.slug in ('fundamentals', 'anger', 'reentry', 'calm-you-can-lend', 'the-house-that-kept-going', 'knowing-again', 'after-action-at-the-door', 'direct-hours', 'unscored-child', 'midcourse-correction');
